server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

# h2
spring:
  datasource:
    url: jdbc:h2:mem:kpsecdb;MODE=MySQL;DB_CLOSE_DELAY=-1
    platform: org.hibernate.dialect.H2Dialect
    username: kpsec
    password: kpsec
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  
  
  # jpa
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
  
  #devtool      
  devtools:
    livereload:
      enabled: true
  freemarker:
    cache: false
    
logging.level:
  org.hibernate.SQL: debug      
  